import{useState}from"react";import{NavLink,Routes,Route}from"react-router-dom";import{LayoutDashboard,FolderKanban,CheckSquare,Users,Settings,Plus,Bell,Menu,MoreHorizontal,LogOut,CircleCheck,Clock3}from"lucide-react";

const projects=[{id:1,name:"Website Redesign",description:"Modernize the company website and improve conversion.",progress:72,status:"In Progress",due:"Sep 24",members:4,tasks:18},{id:2,name:"Mobile Application",description:"Build the first release of the customer mobile app.",progress:45,status:"In Progress",due:"Oct 10",members:6,tasks:24},{id:3,name:"Marketing Campaign",description:"Plan and launch the Q4 digital marketing campaign.",progress:100,status:"Completed",due:"Aug 30",members:5,tasks:15},{id:4,name:"Internal Dashboard",description:"Create analytics and reporting tools for the team.",progress:28,status:"Planning",due:"Oct 28",members:3,tasks:12}];
const initialTasks=[{id:1,title:"Create homepage wireframe",project:"Website Redesign",assignee:"NK",priority:"High",status:"In Progress",due:"Sep 14"},{id:2,title:"Set up MongoDB models",project:"Mobile Application",assignee:"AS",priority:"Medium",status:"Todo",due:"Sep 16"},{id:3,title:"Prepare campaign assets",project:"Marketing Campaign",assignee:"RM",priority:"High",status:"Completed",due:"Sep 10"},{id:4,title:"Build analytics cards",project:"Internal Dashboard",assignee:"PS",priority:"Low",status:"Todo",due:"Sep 20"}];
const team=[["Naina Kumari","Project Manager","NK"],["Aman Singh","Frontend Developer","AS"],["Riya Mehta","UI/UX Designer","RM"],["Priya Sharma","Backend Developer","PS"]];

function Layout({children}){const[open,setOpen]=useState(false);const nav=[["/",LayoutDashboard,"Dashboard"],["/projects",FolderKanban,"Projects"],["/tasks",CheckSquare,"Tasks"],["/team",Users,"Team"],["/settings",Settings,"Settings"]];return <div className="min-h-screen flex bg-slate-50"><aside className={`fixed z-30 inset-y-0 left-0 w-64 bg-slate-950 text-white transform ${open?"translate-x-0":"-translate-x-full"} lg:translate-x-0 transition-transform`}><div className="h-16 flex items-center px-6 border-b border-white/10 text-xl font-bold">TaskFlow<span className="text-indigo-400">.</span></div><nav className="p-4 space-y-1">{nav.map(([to,I,label])=><NavLink key={to} to={to} onClick={()=>setOpen(false)} className={({isActive})=>`flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-medium ${isActive?"bg-indigo-600":"text-slate-300 hover:bg-white/10"}`}><I size={19}/>{label}</NavLink>)}</nav><div className="absolute bottom-5 left-4 right-4 bg-white/5 rounded-2xl p-4"><div className="text-xs text-slate-400">Workspace</div><b>Naina's Team</b><button className="mt-4 text-xs text-slate-400 flex gap-2"><LogOut size={14}/>Sign out</button></div></aside>{open&&<div onClick={()=>setOpen(false)} className="fixed inset-0 bg-black/40 z-20 lg:hidden"/>}<main className="lg:ml-64 flex-1"><header className="h-16 bg-white border-b flex items-center justify-between px-4 sm:px-6 sticky top-0 z-10"><button onClick={()=>setOpen(true)} className="lg:hidden"><Menu/></button><div className="font-bold">Project Management System</div><div className="flex items-center gap-3"><Bell size={19}/><div className="w-9 h-9 rounded-full bg-indigo-100 text-indigo-700 flex items-center justify-center font-bold text-sm">NK</div></div></header><div className="p-4 sm:p-6 lg:p-8">{children}</div></main></div>}

function Stat({I,label,value}){return <div className="bg-white border rounded-2xl p-5 shadow-sm"><div className="w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center"><I size={20}/></div><div className="mt-4 text-2xl font-bold">{value}</div><div className="text-sm text-slate-500 mt-1">{label}</div></div>}
function ProjectRow({p}){return <div><div className="flex justify-between"><div><b>{p.name}</b><div className="text-xs text-slate-500 mt-1">{p.tasks} tasks · due {p.due}</div></div><b>{p.progress}%</b></div><div className="h-2 bg-slate-100 rounded-full mt-3"><div className="h-full bg-indigo-600 rounded-full" style={{width:p.progress+"%"}}/></div></div>}
function TaskRow({t}){return <div className="flex gap-3"><div className={`mt-1.5 w-2.5 h-2.5 rounded-full ${t.status==="Completed"?"bg-emerald-500":t.status==="In Progress"?"bg-amber-500":"bg-slate-300"}`}/><div><b className="text-sm">{t.title}</b><div className="text-xs text-slate-500">{t.project} · {t.due}</div></div></div>}

function Dashboard(){return <div className="space-y-6"><div className="flex flex-col sm:flex-row justify-between gap-3"><div><h1 className="text-2xl font-bold">Good morning, Naina 👋</h1><p className="text-slate-500">Here's what's happening with your projects today.</p></div><button className="bg-indigo-600 text-white px-4 py-2.5 rounded-xl flex gap-2 items-center justify-center font-semibold"><Plus size={18}/>New Project</button></div><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4"><Stat I={FolderKanban} label="Total Projects" value="12"/><Stat I={CheckSquare} label="Total Tasks" value="69"/><Stat I={CircleCheck} label="Completed Tasks" value="42"/><Stat I={Clock3} label="Pending Tasks" value="27"/></div><div className="grid xl:grid-cols-3 gap-6"><section className="xl:col-span-2 bg-white border rounded-2xl p-5 shadow-sm"><div className="flex justify-between mb-5"><h2 className="font-bold">Active Projects</h2><NavLink to="/projects" className="text-indigo-600 text-sm">View all</NavLink></div><div className="space-y-5">{projects.slice(0,3).map(p=><ProjectRow key={p.id} p={p}/>)}</div></section><section className="bg-white border rounded-2xl p-5 shadow-sm"><div className="flex justify-between mb-5"><h2 className="font-bold">Recent Tasks</h2><NavLink to="/tasks" className="text-indigo-600 text-sm">View all</NavLink></div><div className="space-y-4">{initialTasks.map(t=><TaskRow key={t.id} t={t}/>)}</div></section></div></div>}

function Projects(){const[items,setItems]=useState(projects);return <div className="space-y-6"><div className="flex justify-between"><div><h1 className="text-2xl font-bold">Projects</h1><p className="text-slate-500">Manage and track all your projects.</p></div><button onClick={()=>setItems([{id:Date.now(),name:"New Project",description:"New project description.",progress:0,status:"Planning",due:"Oct 31",members:1,tasks:0},...items])} className="bg-indigo-600 text-white px-4 py-2.5 rounded-xl flex gap-2 items-center"><Plus size={18}/>Add Project</button></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{items.map(p=><div key={p.id} className="bg-white border rounded-2xl p-5 shadow-sm"><div className="flex justify-between"><div className="w-11 h-11 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center"><FolderKanban/></div><MoreHorizontal className="text-slate-400"/></div><h3 className="font-bold mt-4">{p.name}</h3><p className="text-sm text-slate-500 mt-2">{p.description}</p><div className="mt-5"><ProjectRow p={p}/></div><div className="mt-5 pt-4 border-t text-xs text-slate-500 flex justify-between"><span>{p.members} members</span><span>{p.status}</span></div></div>)}</div></div>}

function Tasks(){const[tasks,setTasks]=useState(initialTasks);const[filter,setFilter]=useState("All");const visible=tasks.filter(t=>filter==="All"||t.status===filter);const cycle=id=>setTasks(tasks.map(t=>t.id===id?{...t,status:t.status==="Todo"?"In Progress":t.status==="In Progress"?"Completed":"Todo"}:t));return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Tasks</h1><p className="text-slate-500">Track work across all projects.</p></div><div className="flex gap-2 flex-wrap">{["All","Todo","In Progress","Completed"].map(x=><button key={x} onClick={()=>setFilter(x)} className={`px-4 py-2 rounded-lg text-sm ${filter===x?"bg-slate-900 text-white":"bg-white border"}`}>{x}</button>)}</div><div className="bg-white border rounded-2xl overflow-x-auto shadow-sm"><table className="w-full min-w-[700px] text-sm"><thead className="bg-slate-50"><tr><th className="text-left p-4">Task</th><th className="text-left p-4">Project</th><th className="text-left p-4">Priority</th><th className="text-left p-4">Status</th><th className="text-left p-4">Due</th></tr></thead><tbody>{visible.map(t=><tr key={t.id} className="border-t"><td className="p-4"><button onClick={()=>cycle(t.id)} className="font-semibold text-left hover:text-indigo-600">{t.title}</button><div className="text-xs text-slate-400">{t.assignee}</div></td><td className="p-4">{t.project}</td><td className="p-4">{t.priority}</td><td className="p-4"><span className="bg-indigo-50 text-indigo-600 px-2.5 py-1 rounded-full text-xs font-semibold">{t.status}</span></td><td className="p-4 text-slate-500">{t.due}</td></tr>)}</tbody></table></div></div>}

function Team(){return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Team</h1><p className="text-slate-500">People working in your workspace.</p></div><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-5">{team.map(([name,role,initials])=><div key={name} className="bg-white border rounded-2xl p-5 shadow-sm"><div className="w-14 h-14 rounded-full bg-indigo-100 text-indigo-700 flex items-center justify-center font-bold">{initials}</div><h3 className="font-bold mt-4">{name}</h3><p className="text-sm text-indigo-600">{role}</p><p className="text-xs text-slate-500 mt-3">{name.toLowerCase().replaceAll(" ",".")}@example.com</p></div>)}</div></div>}
function SettingsPage(){return <div className="max-w-2xl space-y-6"><h1 className="text-2xl font-bold">Settings</h1><div className="bg-white border rounded-2xl p-6 space-y-5"><label className="block text-sm font-semibold">Workspace name<input defaultValue="Naina's Team" className="mt-2 w-full border rounded-xl px-4 py-3 font-normal"/></label><label className="block text-sm font-semibold">Email notifications<select className="mt-2 w-full border rounded-xl px-4 py-3 font-normal"><option>Enabled</option><option>Disabled</option></select></label><button className="bg-indigo-600 text-white px-5 py-2.5 rounded-xl font-semibold">Save Changes</button></div></div>}
export default function App(){return <Layout><Routes><Route path="/" element={<Dashboard/>}/><Route path="/projects" element={<Projects/>}/><Route path="/tasks" element={<Tasks/>}/><Route path="/team" element={<Team/>}/><Route path="/settings" element={<SettingsPage/>}/></Routes></Layout>}